### ISSUE TITLE
Failed to compare two json files

### ISSUE THREAD

**Issue by mashenka123** [Krutov777/python-project-lvl2#6]
I want to use this CLI to compare two json files, I tested with python3.8 and python3.9, neither of them can work, could you please check and kindly give a fix? Thank you!  I read the code but found no issue, I only have a little experience on python..

gendiff "/root/Desktop/webold.json" "/root/Desktop/webnew.json" -f text                                                              2 ⨯
Traceback (most recent call last):
  File "/usr/local/bin/gendiff", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/gendiff/cli.py", line 34, in main
    args.second_filef, 
AttributeError: 'Namespace' object has no attribute 'second_filef'

my json file format is like:
{
  "key":"value",
  "key1":"value1"
}

**Comment by Krutov777** [comment]
Try with this query. Also, if you are in a directory with the files you want to compare, you don't have to specify an absolute path. That is, you can write just the name of the files.

gendiff /root/Desktop/webold.json  /root/Desktop/webnew.json --format text

or 

gendiff webold.json  webnew.json --format text
